AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Demand Letter Generator - Simple Express Lambda Deployment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  
  OpenRouterApiKey:
    Type: String
    NoEcho: true
    Description: OpenRouter API Key
  
  DatabaseHost:
    Type: String
    Description: Database host (RDS endpoint or localhost for testing)
  
  DatabasePort:
    Type: Number
    Default: 5432
    Description: Database port
  
  DatabaseName:
    Type: String
    Default: demand_letter_generator
    Description: Database name
  
  DatabaseUser:
    Type: String
    Description: Database user
  
  DatabasePassword:
    Type: String
    NoEcho: true
    Description: Database password
  
  JwtSecret:
    Type: String
    NoEcho: true
    Description: JWT secret key
  
  CorsOrigin:
    Type: String
    Default: '*'
    Description: CORS origin

Globals:
  Function:
    Timeout: 60  # Increased for AI operations
    MemorySize: 1024
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        AWS_LAMBDA_FUNCTION_NAME: !Sub '${ApiHandler}-${Environment}'  # Detect Lambda environment
        DB_HOST: !Ref DatabaseHost
        DB_PORT: !Ref DatabasePort
        DB_NAME: !Ref DatabaseName
        DB_USER: !Ref DatabaseUser
        DB_PASSWORD: !Ref DatabasePassword
        JWT_SECRET: !Ref JwtSecret
        S3_BUCKET_DOCUMENTS: !Ref DocumentsBucket
        S3_BUCKET_PROCESSED: !Ref ProcessedBucket
        S3_BUCKET_EXPORTS: !Ref ExportsBucket
        OPENROUTER_API_KEY: !Ref OpenRouterApiKey
        OPENROUTER_MODEL: gpt-4o
        CORS_ORIGIN: !Ref CorsOrigin
        AWS_REGION: !Ref AWS::Region

Resources:
  # S3 Buckets
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'demand-letter-generator-${Environment}-documents'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90

  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'demand-letter-generator-${Environment}-processed'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ExportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'demand-letter-generator-${Environment}-exports'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldExports
            Status: Enabled
            ExpirationInDays: 30

  # IAM Role for Lambda Functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub '${DocumentsBucket}/*'
                  - !Sub '${DocumentsBucket}'
                  - !Sub '${ProcessedBucket}/*'
                  - !Sub '${ProcessedBucket}'
                  - !Sub '${ExportsBucket}/*'
                  - !Sub '${ExportsBucket}'

  # Single Express Lambda Function (no Events to avoid SAM circular dependency)
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend
      Handler: dist/lambda.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60  # Increased for AI operations
      MemorySize: 1024  # Sufficient for AI processing

  # API Gateway RestApi (plain CloudFormation, no SAM transform)
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'demand-letter-generator-${Environment}'
      EndpointConfiguration:
        Types:
          - REGIONAL
      BinaryMediaTypes:
        - "image/*"
        - "application/pdf"
        - "application/msword"
        - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

  # API Gateway Proxy Resource
  ApiGatewayProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: '{proxy+}'

  # API Gateway Method for root
  ApiGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiHandler.Arn}/invocations'

  # API Gateway Method for proxy
  ApiGatewayProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiGatewayProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiHandler.Arn}/invocations'

  # API Gateway Deployment (no explicit DependsOn - CloudFormation will infer from Method references)
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref Environment

  # Lambda Permission (no SourceArn to break circular dependency - less secure but necessary)
  ApiGatewayLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiHandler
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'
  
  DocumentsBucketName:
    Description: S3 bucket for uploaded documents
    Value: !Ref DocumentsBucket
    Export:
      Name: !Sub '${AWS::StackName}-DocumentsBucket'
  
  ProcessedBucketName:
    Description: S3 bucket for processed documents
    Value: !Ref ProcessedBucket
    Export:
      Name: !Sub '${AWS::StackName}-ProcessedBucket'
  
  ExportsBucketName:
    Description: S3 bucket for exports
    Value: !Ref ExportsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ExportsBucket'

